---
- name: Pull Docker Image of freshlyjuiced/spe-mini-proj
  hosts: all
  tasks:
    - name: Get Running Containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop Running Containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

    - name: Remove Stopped Docker Containers
      shell: |
        docker rm $(docker ps -a -q);
      when: docker_info.containers != 0

    - name: Get all Docker Images
      docker_host_info:
        images: yes
        verbose_output: yes
      register: image_info

    - name: Remove all Docker Images
      docker_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ image_info.images | map(attribute='Id') | list }}"

    - name: Pull Calculator Image
      docker_image:
        name: freshlyjuiced/spe-mini-proj
        source: pull